// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc1ulZIVdGiD898DHKTfVOleChUKGjZ04',
    appId: '1:454537785537:web:6599f42ab28c3703826440',
    messagingSenderId: '454537785537',
    projectId: 'fluttre-female-course-2026',
    authDomain: 'fluttre-female-course-2026.firebaseapp.com',
    storageBucket: 'fluttre-female-course-2026.firebasestorage.app',
    measurementId: 'G-EMYL7V3W0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCau4kvlhoR3kE27umXnW7FLOc0v0Wtw1U',
    appId: '1:454537785537:android:ca480bd9e939e1d8826440',
    messagingSenderId: '454537785537',
    projectId: 'fluttre-female-course-2026',
    storageBucket: 'fluttre-female-course-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn-g8Prba5TtlTwjOumO-fNj2y7dOM9WU',
    appId: '1:454537785537:ios:4a54f15f4c114a1c826440',
    messagingSenderId: '454537785537',
    projectId: 'fluttre-female-course-2026',
    storageBucket: 'fluttre-female-course-2026.firebasestorage.app',
    iosBundleId: 'com.example.firebaseInit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn-g8Prba5TtlTwjOumO-fNj2y7dOM9WU',
    appId: '1:454537785537:ios:4a54f15f4c114a1c826440',
    messagingSenderId: '454537785537',
    projectId: 'fluttre-female-course-2026',
    storageBucket: 'fluttre-female-course-2026.firebasestorage.app',
    iosBundleId: 'com.example.firebaseInit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc1ulZIVdGiD898DHKTfVOleChUKGjZ04',
    appId: '1:454537785537:web:9351e10edf7775c0826440',
    messagingSenderId: '454537785537',
    projectId: 'fluttre-female-course-2026',
    authDomain: 'fluttre-female-course-2026.firebaseapp.com',
    storageBucket: 'fluttre-female-course-2026.firebasestorage.app',
    measurementId: 'G-52C5Z3V5VZ',
  );
}
